Attribute VB_Name = "modMXMLC"
Public Const OUTPUT_PATH As String = " -output="
Public Const INCLUDE_LIBRARIES As String = " -include-libraries="
Public Const COMPILE_DEBUG As String = " -debug="
Public Const SERVICES As String = " -services="
Public Const CONTEXT_ROOT As String = " -context-root="
